-- Ordem de execução (FASE 2 + FASE 3 + FASE 4 + FASE 5 + FASE 6)
-- 1) database/migrations/001_core_multitenant.sql
-- 2) database/migrations/002_auth_onboarding_security.sql
-- 3) database/migrations/003_billing_debito.sql
-- 4) database/migrations/004_whatsapp_instances.sql
-- 5) database/migrations/005_inbox_crm_pipeline.sql
-- 6) database/seeds/001_subscription_statuses.sql
-- 7) database/seeds/002_roles_permissions.sql
-- 8) database/seeds/003_plans.sql
-- 9) database/seeds/004_master_admin.sql
